# Generated by Django 6.0.7 on 2026-08-12 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auther',
            new_name='author',
        ),
    ]
